sudo: required
services: 
  - docker
  
before_install: 
  - docker build -t polatsbf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true polatsbf/docker-react npm run test -- --coverage